# Generated by Django 4.2 on 2026-02-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
